em_constants:
  capacity_utilization: 0.95
mqtt:
  host: mqtt-server
  port: 1883
  user: <user>              # Ergänzte User-Anmeldung
  password: <password>      # Ergänztes Passwort
  topics:
    z1_zaehler: huehnerhaus/powermeter/z1/actual/mean
    current_em_mode: huehnerhaus/batcontrol/inverters/0/em_mode
    current_em_power: huehnerhaus/batcontrol/inverters/0/em_power
    set_em_power: huehnerhaus/batcontrol/inverters/0/em_power/set
    set_em_mode: huehnerhaus/batcontrol/inverters/0/em_mode/set
    batcontrol_mode: huehnerhaus/batcontrol/mode
    batcontrol_status: huehnerhaus/batcontrol/status
    soc: huehnerhaus/evcc/site/battery/1/soc
    grid_power: huehnerhaus/evcc/site/grid/power
    ev_connected: huehnerhaus/evcc/loadpoints/1/connected
    ev_charge_mode: huehnerhaus/evcc/loadpoints/1/mode
    pv_power: huehnerhaus/evcc/site/pvPower
    home_power: huehnerhaus/evcc/site/homePower
    batcontrol_max_capacity: huehnerhaus/batcontrol/max_energy_capacity
    batcontrol_stored_energy: huehnerhaus/batcontrol/stored_energy_capacity
    batcontrol_fcst_solar: huehnerhaus/batcontrol/FCST/production
    batcontrol_fcst_net_consumption: huehnerhaus/batcontrol/FCST/net_consumption
  send_topics:
    activate_zp: huehnerhaus/wp-ems/zp_activate
    solar_surplus: huehnerhaus/wp-ems/solar_surplus_wh
    power_feed_in: huehnerhaus/wp-ems/power_feed_in
    current_power: huehnerhaus/wp-ems/current_power
    em_constant_base_topic: huehnerhaus/wp-ems
    car_ready_to_charge: huehnerhaus/wp-ems/car_ready_to_charge